Repository bellshade/Rust, pull requests merged in 2022-10, with the labels that each got.

#12 doc: add deref trait
  extras/smart_pointers/02_deref_trait.md
Labels: doc

#13 docs: Update readme description
  README.md
Labels: documentation

#14 fix: restructure project and use cargo workspace
  Cargo.toml
  algorithms/Cargo.toml
  algorithms/src/lib.rs
  algorithms/src/sorting/bogo_sort.rs
  algorithms/src/sorting/mod.rs
  basics/01_introduction/src/lib.rs
  basics/02_variables/src/lib.rs
  basics/03_functions/src/lib.rs
  basics/04_ownership/src/lib.rs
  basics/05_enumeration_dan_pattern_matching/src/lib.rs
  basics/Cargo.toml
  basics/src/lib.rs
  extras/Cargo.toml
  extras/src/lib.rs
  intermediate/src/lib.rs
Labels: bug
